package roadcompany;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
        JFrame frame=new JFrame("CardLayout do sistema");
    
    public JanelaPrincipal() {
        initComponents();
        CardLayout c1 = new CardLayout();
        panelCont.add(TelaGeral,"1");
        panelCont.add(CadastroVeiculo,"2");
        c1.show(panelCont,"1");
        
        frame.add(panelCont);
        
        btCVeiculo.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                c1.show(panelCont,"2");
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCont = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TelaGeral = new javax.swing.JPanel();
        btCVeiculo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        CadastroVeiculo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 620));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 620));
        getContentPane().setLayout(null);

        panelCont.setLayout(null);

        jLabel2.setText("TESTE");
        panelCont.add(jLabel2);
        jLabel2.setBounds(240, 100, 30, 14);

        getContentPane().add(panelCont);
        panelCont.setBounds(300, 90, 100, 100);

        TelaGeral.setPreferredSize(new java.awt.Dimension(800, 620));
        TelaGeral.setLayout(null);

        btCVeiculo.setText("Cadastrar Veículo");
        btCVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCVeiculoActionPerformed(evt);
            }
        });
        TelaGeral.add(btCVeiculo);
        btCVeiculo.setBounds(50, 40, 200, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ad\\Documents\\GitHub\\frameworkpds\\RoadCompany\\src\\roadcompany\\img\\mainwindow.jpg")); // NOI18N
        TelaGeral.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        jTextField1.setText("jTextField1");
        TelaGeral.add(jTextField1);
        jTextField1.setBounds(510, 120, 59, 20);

        getContentPane().add(TelaGeral);
        TelaGeral.setBounds(0, 0, 800, 620);

        CadastroVeiculo.setLayout(null);
        getContentPane().add(CadastroVeiculo);
        CadastroVeiculo.setBounds(250, 60, 100, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCVeiculoActionPerformed
        
    }//GEN-LAST:event_btCVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CadastroVeiculo;
    private javax.swing.JPanel TelaGeral;
    private javax.swing.JButton btCVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelCont;
    // End of variables declaration//GEN-END:variables
}
